services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
